// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFG6aBfY9AfAYriCc5BrcELJuWZ3fUM9g',
    appId: '1:101060568384:web:7f84f8ab311f502d0746a5',
    messagingSenderId: '101060568384',
    projectId: 'stanfordapp-15a49',
    authDomain: 'stanfordapp-15a49.firebaseapp.com',
    storageBucket: 'stanfordapp-15a49.firebasestorage.app',
    measurementId: 'G-E7WDDY1SHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIiQn6EHO-dYnvkxm2XNVKe6nM0MuvqVU',
    appId: '1:101060568384:android:e90c86ab367c044b0746a5',
    messagingSenderId: '101060568384',
    projectId: 'stanfordapp-15a49',
    storageBucket: 'stanfordapp-15a49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLL4cgkr5TWm0KEhaou8M2XG5WDBBlQjE',
    appId: '1:101060568384:ios:48e1ad842fcdea370746a5',
    messagingSenderId: '101060568384',
    projectId: 'stanfordapp-15a49',
    storageBucket: 'stanfordapp-15a49.firebasestorage.app',
    iosBundleId: 'com.example.stanfordBinet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLL4cgkr5TWm0KEhaou8M2XG5WDBBlQjE',
    appId: '1:101060568384:ios:48e1ad842fcdea370746a5',
    messagingSenderId: '101060568384',
    projectId: 'stanfordapp-15a49',
    storageBucket: 'stanfordapp-15a49.firebasestorage.app',
    iosBundleId: 'com.example.stanfordBinet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFG6aBfY9AfAYriCc5BrcELJuWZ3fUM9g',
    appId: '1:101060568384:web:aa0b34bcccff354d0746a5',
    messagingSenderId: '101060568384',
    projectId: 'stanfordapp-15a49',
    authDomain: 'stanfordapp-15a49.firebaseapp.com',
    storageBucket: 'stanfordapp-15a49.firebasestorage.app',
    measurementId: 'G-C31PY5M2P5',
  );
}
